name: Deploy Next.js (Low RAM Fix)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next/,public/,package.json,package-lock.json,next.config.js"
          target: "~/rsa-frontend"

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
        script: |
          # 1. Node/NVM ka rasta set karein
           export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      
          # 2. Project folder mein jayein
          cd ~/rsa-frontend
      
          # 3. Code update karein
          git pull origin main
      
          # 4. Dependencies install karein (Fast method)
          npm ci --production
      
          # 5. Build (t3.small ki RAM bachane ke liye limit ke sath)
          export NODE_OPTIONS="--max-old-space-size=1024"
          npm run build
      
          # 6. PM2 Restart (Agar pehli baar hai toh start karega)
          pm2 restart all || pm2 start npm --name "rsa-frontend" -- start

            
